### ISSUE TITLE
Add top-level "metadata" field

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-spec#65]
Stdpopsim is an important downstream user of Demes, and it looks like we will often need to store the mutation rate with a given model:

https://github.com/popsim-consortium/stdpopsim/pull/839

The right place to do this is in the Demes yaml file. The question is, how do we facilitate this. I see three options:

1. Add a mutation_rate field
2. Allow users to put extra stuff into the yaml, wherever they want
3. Add a top-level "metadata"  (or "extra", or something) field where people can dump whatever they want.

I see pros and cons to all three. Thoughts?

**Comment by grahamgower** [comment]
I've been thinking something like option 3. We'd want this at all scopes though (or at least for: top-level, deme, and epoch).

**Comment by jeromekelleher** [comment]
@molpopgen, @apragsdale, how are you feeling about an optional free-form ``metadata`` field at the top-level and in the Deme class?

**Comment by grahamgower** [comment]
Thinking on the `mutation_rate` field a bit more... Suppose a simulator simulates demes graphs now, without considering a mutation_rate field (in the metadata, or wherever). Next, suppose we add the mutation_rate as a top-level field in the spec, and bump the spec_version. This is a **strong** backwards incompatibility---to avoid simulating the wrong thing in the future, simulators must decide on a maximum spec_version they support and then explicitly throw an error for graphs with higher versions, instead of simulating. The simulator must do this even if the newer spec version fixes a bug, because there's no way to know it isn't backwards incompatible. The mutation_rate is an obvious example, but of course this applies to anything else.

So we almost certainly want to include a spec_version field now.

**Comment by jeromekelleher** [comment]
Yeah, you **always** need a version number. Especially if you think you don't!

**Comment by apragsdale** [comment]
I think I agree with everyone here (though it's a bit hard to fully know the pros and cons of the various options). I agree that there does need to be somewhere to put a mutation rate or other extra information that is relevant to the model that doesn't fit within the specific fields we've provided so far. A free-form metadata field makes a lot of sense to me, which we would then just have to document to try to encourage consistent usage by various users?

**Comment by molpopgen** [comment]
I'm of the same opinion as @apragsdale

**Comment by jeromekelleher** [comment]
Looping back around to this, this seems like the last major thing we need to close up before tagging the 1.0 spec. Are we going to include it in 1.0, or wait until 1.1? Since we know we're going to add it, maybe it would be best to do it for 1.0?

**Comment by grahamgower** [comment]
Now sounds like a good time to get it into the spec. And I agree that metadata fields should be objects.

**Comment by jeromekelleher** [comment]
I've been thinking more about this in the background, and I'm very much of the opinion we should keep this simple. My proposal is we add a single top-level field called ``metadata``, which people can do whatever they want with. Yes, there's an argument for putting in metadata fields at every level, but we don't *need* them initially so I vote we don't bother. They can be added later without too much disruption if/when needed.

Regarding the name, we've gone around things like ``info``, ``extra`` etc, but I think, on reflection, that ``metadata`` is more descriptive. The distinction between data and metadata here is crystal clear: data is stuff that's defined in the model, and ``metadata`` is stuff that isn't. The most important thing we want to use this for initially is to add important information **about** the model, and ``metadata`` is the correct description for this information, IMO.

**Comment by molpopgen** [comment]
I'm on board w/top-level metadata, and agree we can add stuff to the other levels later.

**Comment by apragsdale** [comment]
Sounds like a great plan to me, happy with the name "metadata".

> add a single top-level field called `metadata`, which people can do whatever they want with

"whatever they want" within valid YAML/JSON still, I presume? I'm not sure how much behind-the-scenes work will need to be put in to the schema for it.

**Comment by grahamgower** [comment]
Sure, that sounds like a fine plan.

> "whatever they want" within valid YAML/JSON still, I presume? I'm not sure how much behind-the-scenes work will need to be put in to the schema for it.

For the schema, I think we just need to require that `metadata` is an `object` with `default: {}`, no required properties, and `additionalProperties: true`. This works fairy easily for the Python parsers, because one just parses the field into a dict and it's basically job done (anything else is up to the user).

For the C parser, it's slightly more awkward because right now there's no dict data structure that can be passed back to the user. Everything is currently parsed into structs or lists. Leaving it to the user to parse the metadata "object" node and its descendents would expose implementation details of the parser to the user, which is of course not ideal. I see two reasonable approaches that avoid adding a hash table just to support the metadata:
 - translate dicts into lists of key/value tuples, with arbitrary nesting allowed
 - return the metadata field as a raw unparsed json string (which means translating the yaml into json).

**Comment by jeromekelleher** [comment]
That is a gnarly problem with the C parser @grahamgower. My suggestion would be to simply say that the C parser currently doesn't provide access to the ``metadata`` field - it seems unlikely that people using the C version are going to *need* to look into the metadata anyway.
